#!/usr/bin/env node

if (process.argv.length != 4) {
  console.log("usage: script/cson2json <github_repo> <name_of_cson>");
  process.exit(1);
}

var fs = require('fs');
var path = require('path');
var exec = require('child_process').exec;

var github_repo = process.argv[2];
var lang_name = process.argv[3];
var path_to_cson = path.join("vendor", "sources", lang_name, "grammars", lang_name) + ".cson";
var json_filename = path.join("languages", lang_name + ".json");

console.log("Fetching git://github.com/" + github_repo);
exec("git submodule add -f git://github.com/" + github_repo + " vendor/sources/" + lang_name, function(error, stdout, stderr) {
  if (error !== null) {
    console.error(stderr);
    console.error('exec error: ' + error);
    process.exit(1);
  }
  console.log("Fetched! Converting " + path_to_cson + " to " + json_filename);
  exec("cson2json " + path_to_cson + " > " + json_filename, function (error, stdout, stderr) {
    if (error !== null) {
      console.error(stderr);
      console.error('exec error: ' + error);
    }
    fs.readFile(json_filename, 'utf8', function (err, data) {
      if (err) { return console.error(err); }
      var match = "";
      if (match = /\\x\{(.+?)\}/g.exec(data)) {
        console.log("Found some characters to remove:");
        console.log(match);
        data = data.replace(/\\x\{(.+?)\}/g, "\\x$1");
      }
      fs.writeFileSync(json_filename, JSON.stringify(JSON.parse(data), null, 2));
    });
  });
});
