#!/bin/sh

set -e
export CC=gcc

git submodule init
git submodule update --recursive

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems 2>&1 > /dev/null || {
  bundle install --binstubs bin --path vendor/gems --quiet
}
