#!/usr/bin/env node

if (process.argv.length != 3) {
	console.log("usage: script/cson2json <filePath>");
	process.exit(1);
}

var path = require('path');
var exec = require('child_process').exec;

var path_to_cson = path.join(__dirname, "..", process.argv[2]);
var json_filename = path.join("languages", path.basename(process.argv[2], ".cson") + ".json");

exec("cson2json " + path_to_cson + " > " + json_filename,
  function (error, stdout, stderr) {
    if (error !== null) {
      console.error(stderr);
      console.error('exec error: ' + error);
    }
});
